global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka1:7071', 'kafka2:7072']
    metrics_path: '/metrics'

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:7000']

  - job_name: 'faust'
    static_configs:
      - targets: ['faust:6066']

  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:4040']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9114']
